"""add_matrix_metadata_columns

Revision ID: 6324df617216
Revises: 812a6467f1d9
Create Date: 2026-02-11 20:23:53.252084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6324df617216'
down_revision: Union[str, Sequence[str], None] = '812a6467f1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distance_matrices', sa.Column('stop_count', sa.Integer(), nullable=True))
    op.add_column('distance_matrices', sa.Column('build_time_seconds', sa.Float(), nullable=True))
    op.add_column('distance_matrices', sa.Column('stop_ids_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distance_matrices', 'stop_ids_json')
    op.drop_column('distance_matrices', 'build_time_seconds')
    op.drop_column('distance_matrices', 'stop_count')
    # ### end Alembic commands ###
