"""update bus depot_id ondelete set null

Revision ID: 6881d002294e
Revises: a1f3db0d46c3
Create Date: 2026-02-10 11:54:21.364073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6881d002294e'
down_revision: Union[str, Sequence[str], None] = 'a1f3db0d46c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('buses_depot_id_fkey'), 'buses', type_='foreignkey')
    op.create_foreign_key(None, 'buses', 'depots', ['depot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buses', type_='foreignkey')
    op.create_foreign_key(op.f('buses_depot_id_fkey'), 'buses', 'depots', ['depot_id'], ['id'])
    # ### end Alembic commands ###
