"""Add cascade delete to demand

Revision ID: 812a6467f1d9
Revises: 6881d002294e
Create Date: 2026-02-10 12:13:46.830240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812a6467f1d9'
down_revision: Union[str, Sequence[str], None] = '6881d002294e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('demand_stop_id_fkey'), 'demand', type_='foreignkey')
    op.create_foreign_key(None, 'demand', 'stops', ['stop_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demand', type_='foreignkey')
    op.create_foreign_key(op.f('demand_stop_id_fkey'), 'demand', 'stops', ['stop_id'], ['id'])
    # ### end Alembic commands ###
