"""remove semester from demand

Revision ID: 96276c1085ab
Revises: 42da2c907c08
Create Date: 2026-04-03 13:01:22.968786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96276c1085ab'
down_revision: Union[str, Sequence[str], None] = '42da2c907c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demand', 'semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand', sa.Column('semester', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
