"""initial_schema

Revision ID: a1f3db0d46c3
Revises: 
Create Date: 2026-02-06 16:24:47.553347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f3db0d46c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distance_matrices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('matrix_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('routes_json', sa.JSON(), nullable=False),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stop_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stops_stop_code'), 'stops', ['stop_code'], unique=True)
    op.create_table('buses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bus_no', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demand')
    op.drop_table('buses')
    op.drop_index(op.f('ix_stops_stop_code'), table_name='stops')
    op.drop_table('stops')
    op.drop_table('solutions')
    op.drop_table('distance_matrices')
    op.drop_table('depots')
    # ### end Alembic commands ###
